version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    working_directory: ~/talkie
    environment:
      - TZ: "/usr/share/zoneinfo/Asia/Tokyo"

  yarn_cache_config: &yarn_cache_config
    key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  yarn_restore_cache: &yarn_restore_cache
    restore_cache:
      <<: *yarn_cache_config
      name: Restore yarn cache

  yarn_save_cache: &yarn_save_cache
    save_cache:
      <<: *yarn_cache_config
      name: Save yarn cache

  system_info: &system_info
    run:
      name: System infomation
      command: |
        echo "Node $(node -v)"
        echo "Yarn v$(yarn --version)"

  deps: &deps
    run:
      name: Install dependencies
      command: yarn install --ignore-engines

jobs:
  run_test:
    <<: *container_config
    steps:
      - checkout
      - *system_info
      - *yarn_restore_cache
      - *deps
      - *yarn_save_cache

      - run:
          name: Lint
          command: make lint

      - run:
          name: Production build
          command: make build NODE_ENV=production

      # - run:
      #     name: Test
      #     command: make test

workflows:
  version: 2

  test:
    jobs:
      - run_test
